Footer changes
100Automations/Website pull request #152
Opened 2021-02-09 21:56 UTC by mcspach

Addresses #148 by fixing positioning and content on the footer element.
please see comment/images on issue for details.

2021-02-11 02:53 UTC, mcspach commented
The last commit addresses spacing issues mentioned in Wed meeting, changes path for icon imgs, and adds all links to social.
Should be ready for merge.

2021-02-12 18:57 UTC, drubgrubby requested changes
@mcspach - This looks great!  I've suggested a couple of nerdy, minor changes, but really nice work.

2021-02-12 18:57 UTC, drubgrubby commented on _includes/footer.html
> +<footer class="footer mdl-mini-footer">
This references a .footer class that doesn't seem to exist anywhere.  (Unless I'm not seeing it.)  If it doesn't exist, I'd recommend removing the reference to it.

2021-02-12 18:57 UTC, drubgrubby commented on _includes/footer.html
> +      <p class="">100 Automations is one of the many projects at Hack&nbsp;for&nbsp;LA, Code&nbsp;for&nbsp;America’s Los&nbsp;Angeles&nbsp;chapter.
Very clever to use html entities to keep the names from breaking. I'm going to steal that.

2021-02-12 18:57 UTC, drubgrubby commented on _sass/includes/footer.scss
> +  .mdl-mini-footer__link-list {
This is super-minor, but I mention it nonetheless. 

When you cross over the 760px width threshold, the line of text jumps up or down (depending on which direction you are going) just a bit, like one line-height. It seem to be that the flex boxes surrounding the icons changes size, which pushes the text up or drops it down.

<img width="699" alt="Screen Shot 2021-02-12 at 10 38 21 AM" src="https://user-images.githubusercontent.com/68244054/107809808-8bfe1e00-6d20-11eb-96ee-a94d06dbd267.png">
<img width="695" alt="Screen Shot 2021-02-12 at 10 38 31 AM" src="https://user-images.githubusercontent.com/68244054/107809851-99b3a380-6d20-11eb-8fd3-066c0bf51a6c.png">

You might try constraining the height of the flexbox, or something similar, to keep this from happening.  As I said, super minor, but if I noticed it, someone else will.

2021-02-12 23:15 UTC, mcspach commented
<img width="1406" alt="Screen Shot 2021-02-12 at 3 08 34 PM" src="https://user-images.githubusercontent.com/38964454/107832188-a21dd580-6d44-11eb-8572-a6b2e3ae17f4.png">
<img width="482" alt="Screen Shot 2021-02-12 at 3 08 54 PM" src="https://user-images.githubusercontent.com/38964454/107832192-a3e79900-6d44-11eb-80c8-7e3034970e44.png">

^^ Above is img from desktop and mobile ^^
-I am unsure about the small padding change that happens at 760px. The change is very small, but it may have to to with the Material Design classes.
-This last commit will get rid of the unused 'footer' class.

2021-02-14 05:46 UTC, daniellex0 commented
The CSS looks good to me 👍

2021-02-16 20:31 UTC, mdothman commented
I've looked over the code and think you did a spectacular job!

2021-02-16 20:33 UTC, merged

2021-02-16 20:33 UTC, mdothman commented
Your code looks spectacular, great job. Fixes issue #148